name: Semantic release

on:
  push:
    branches: [main, beta]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm install --force
    - name: Install semantic-release extra plugins
      run: npm install --force --save-dev @semantic-release/changelog @semantic-release/git        
    - name: Release
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
